services:
  photography-portfolio:
    image: ghcr.io/adrianvillanueva997/photography-portfolio:latest
    restart: unless-stopped
    container_name: photography-portfolio
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.photography-portfolio-redirect-https.redirectscheme.scheme=https
      - traefik.http.middlewares.photography-portfolio-redirect-https.redirectscheme.permanent=true
      - traefik.http.routers.photography-portfolio-http.middlewares=photography-portfolio-redirect-https
      - traefik.http.routers.photography-portfolio-http.rule=Host(`avm.photography`)
      - traefik.http.routers.photography-portfolio-http.entrypoints=http
      - traefik.http.routers.photography-portfolio-https.rule=Host(`avm.photography`)
      - traefik.http.routers.photography-portfolio-https.tls.certresolver=letsencrypt
      - traefik.http.routers.photography-portfolio-https.tls=true
      - traefik.http.routers.photography-portfolio-https.entrypoints=https
      - traefik.http.services.photography-portfolio.loadbalancer.server.port=80
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true

